### ISSUE TITLE
Edit on GitHub daux.io links point to old repository

### ISSUE THREAD

**Issue by danielpcox** [dauxio/daux.io#11]
These Edit on GitHub links point to the justinwalsh/ repo, which doesn't contain the files anymore anyway.

![image](https://user-images.githubusercontent.com/56411/31739173-17b1871a-b41b-11e7-9363-9f39351d76eb.png)

**Comment by onigoetz** [comment]
Hello,

I don't have access to modify the website on http://daux.io/ the website is now https://dauxio.github.io/

On this one the documentation has the right links
