### ISSUE TITLE
File transclusions

### ISSUE THREAD

**Issue by JKingweb** [dauxio/daux.io#112]
As my documentation gets more complex, I'm finding that I want to include as pre-formatted text blocks files which legitimately exist outside the manual distributed with my application e.g. LICENSE, dependency licenses, sample configuration.

Obviously, I'd prefer not to duplicate the maintenance of these, so it would be extremely helpful to have a means of writing references to file, which would be transformed into (in Markdown terms) a fenced code block containing the file contents.

**Comment by onigoetz** [comment]
Hello,

I don't plan to add this feature currently to Daux.

However, what I can recommend is to add a custom Processor that parses some custom syntax to import the files you want.
