### ISSUE TITLE
HTML5shiv hard-coded to default theme

### ISSUE THREAD

**Issue by JKingweb** [dauxio/daux.io#124]
The HTML5shiv JS file is hard-coded to the daux theme [in the layout template](https://github.com/dauxio/daux.io/blob/a1875a2726b8efc8fc1359d9835374a2402498c8/templates/layout/00_layout.php#L45). If a non-default theme directory not containing the daux theme is used, the shiv will not be found, and compatibility is (presumably) reduced.

I'm not certain of the best solution to the problem is, however.

**Comment by onigoetz** [comment]
Yes, I did it because it's wrapped in a conditional comment.

However the HTML5 Shiv is for
> Internet Explorer 6-9, Safari 4.x (and iPhone 3.x), and Firefox 3.x.

Which are dead browsers now, I was thinking of removing this from the template altogether. What do you think ?

**Comment by JKingweb** [comment]
I think it's reasonable to move on. If removing that, though, I'd be interested in also removing Daux's reliance on jQuery, at least outside searching. It shouldn't be too hard to strike the right balance between compatibility and code cleanliness, since what it's being used for is today thoroughly commonplace. I'd be happy to write a patch.

**Comment by onigoetz** [comment]
That’s what I thougt as well for jQuery, however for the search I was thinking about trying preact. That would suit such a use case nicely with a small footprint
