### ISSUE TITLE
bug in drop down menu. pages not showing up

### ISSUE THREAD

**Issue by ArcticSnow** [dauxio/daux.io#132]
We have multiple level (folders and subfolders) in our documentation and when using the drop down menu on the left side, there is a weird behavior where not all content shows up. It behaves as if the drop down menu cannot expand further down. This was tested on different computer and browser software (firefox and chrome).

**Comment by onigoetz** [comment]
Hello, 
my bad, the fix was contributed but not released, you can use version 0.10.1 which fixes this
