### ISSUE TITLE
Search broken?

### ISSUE THREAD

**Issue by bredator** [dauxio/daux.io#140]
Hi there. Great project at all. For a long time, we used it with PHP and live generation of html sites out of Markdown-files. As our manual grows, searching was a feature, our customers wished more and more. And it just don't seem to work. I took the actual unchanged master branch and copied just our docs inside. Then I tried
`daux generate`
and everything was created in the static folder. Opening the index.html and everything looks as expected. But the search field doesn't have any functionality. Looking in index.html, there is a reference to tipuesearch, which is not part of the downloaded archive. If I put the required library inside, there is still no functionality. Pressing Return or clicking the magnifier icon does just nothing. 

How is this possible that search just does nothing, when I use daux.io just out of the box? I don't get it.

**Comment by bredator** [comment]
Forget about it... I don't know why, but I extracted the archive again and generated it all over and it seems to work -_- Sure, after hours of agony, it works 5 minutes after opening an issue...

**Comment by onigoetz** [comment]
Hello,
maybe you have a custom theme ? 

I completely rewrote the search feature a week ago, and the folder is no longer `tipuesearch` maybe that's why ? If you have a custom theme, the references could be incorrect.

Anyway I strongly recommend to use the Docker image or to download through composer.
