### ISSUE TITLE
Cannot read image name with hyphen(-) in `daux serve`

### ISSUE THREAD

**Issue by chw502** [dauxio/daux.io#169]
**Describe the bug**
If image name with hyphen, in `daux serve` cannot display the image.

**To Reproduce**
1. Create a .md file
2. Put test-1.png and add ![](test-1.png) in markdown
3. run `daux serve`
4. Webpage does not show the image

**Expected behavior**
Image(file name with hyphen) should be shown.

**Screenshots**
- In markdown file referred to `![](test-1.png)` and image `test-1.png` is placed in same directory.
- In Chrome debugger throw `GET http://localhost:8085/Test_Dir/test-1.png 404 (Not Found)` error.
![image](https://user-images.githubusercontent.com/29251479/69135192-af252800-0af3-11ea-834d-92d21b42efef.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version 78.0.3904.97

**Comment by onigoetz** [comment]
Hello, thanks for the report. Do you get the same issue if the image doesn't have an hyphen ?

I will make some tests on my side.

**Comment by onigoetz** [comment]
I found the issue that caused this. I fixed it and will release it in a few days. (other bugs to fix at the same time)

**Comment by onigoetz** [comment]
The fixes discussed in this issue are available in [version 0.12](https://github.com/dauxio/daux.io/releases/tag/0.12.0)
