### ISSUE TITLE
Support sorting with "+" to the beginning?

### ISSUE THREAD

**Issue by gerundt** [dauxio/daux.io#18]
I like the feature to sort pages to the end with `-` at the filename. Sometimes I want a page always to the beginning. Could it be an idea to use a `+` for this case?

For example: `/docs/+Cool-Stuff.md`

**Comment by onigoetz** [comment]
Interesting idea.

Just one thing that would prevent it from working correctly : https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations
it seems that FAT 32 doesn't support `+` in file names.

I don't think FAT 32 is still used a lot today (in USB keys maybe ?). But that's still a thing to think about.

Apart from that numbering is already the way to put elements on top.

Current priorities are like this : 

- All files with a number in front
- All files without a number in front
- All files with a `-` and a number in front
- All files with a `-` in front

**Comment by gerundt** [comment]
I think a note in the documentation about the FAT32 problematic could be enough.

For example: Unicodes in filenames don't work with PHP under Windows. So this is a feature what not everybody can use, but it is still inside. :-)

**Comment by onigoetz** [comment]
Good point, I'll check :)

So the order should be 

- All files with a `+` and a number in front
- All files with a `+` in front
- All files with a number in front
- All files without a number in front
- All files with a `-` and a number in front
- All files with a `-` in front

Do you think it's okay like this ?

**Comment by gerundt** [comment]
Since a `+01` is higher then just `+` I think `-01` must be the lower then just `-`:

* `+01_FooBar.md`
* `+FooBar.md`
* `FooBar.md`
* `-FooBar.md`
* `-01_FooBar.md`

**Comment by onigoetz** [comment]
I'm not sure about the two last ones as the contrary is already implemented.

**Comment by onigoetz** [comment]
Done :)
