### ISSUE TITLE
Custom CSS File for small theme modifications

### ISSUE THREAD

**Issue by rhurling** [dauxio/daux.io#180]
**Is your feature request related to a problem? Please describe.**
I'm trying to add 5-10 CSS Rules to change specific elements, but I don't want to create a new theme and have to keep it updated.

**Describe the solution you'd like**
I would love an extra option for the HTML Generator so that I can specify a `custom.css` file to be included.
Something like this:
1. Add `"custom_css": true` in the `html` key of the `config.json`.
2. Create `custom.css` next to `config.json`.
3. `custom.css` is copied into the generated folder and included in the html head.

**Describe alternatives you've considered**
It would probably make vastly easier to make small customizations to any theme and allow easier personalization to the company / brand design (for example changing the Font and some margins).

**Comment by onigoetz** [comment]
Hi, really sorry for the wait, I missed this issue.
I added this feature to the master branch, you can now add a `style.css` file at the root of the documentation.
It's in the master branch and should be released soon

**Comment by onigoetz** [comment]
Hi, this has been released in [Version 0.14.0](https://github.com/dauxio/daux.io/releases/tag/0.14.0)
