### ISSUE TITLE
Multiple images of the same name are causing fatal error

### ISSUE THREAD

**Issue by DeepseaLasagna** [dauxio/daux.io#182]
**Describe the bug**
I have created a nested directory structure in docs. Each subdirectory contains automatically created files, both markdown and graphics. The graphics differ in content but share the same name. When creating the html export the process crashes and does not create all the necessary files:

`result.htmlPHP Fatal error:  Nesting level too deep - recursive dependency? in C:\Users\xx\AppData\Roaming\Composer\vendor\daux\daux.io\libs\Tree\Root.php on line 54`

When I rename the second image, everything works without problem.

**To Reproduce**
1. Copy the simplified example attached to this issue into the daux docs folder
2. run `daux.bat generate`

**Expected behavior**
I'd expect the process to create the static html site regardless of duplicate image names.

**Desktop (please complete the following information):**
 - OS: Windows 10

[daux-img-bug.zip](https://github.com/dauxio/daux.io/files/3988010/daux-img-bug.zip)

**Comment by onigoetz** [comment]
The fixes discussed in this issue are available in [version 0.12](https://github.com/dauxio/daux.io/releases/tag/0.12.0)
