### ISSUE TITLE
daux ignore all non-asci charactor in file name when generating html

### ISSUE THREAD

**Issue by StarDuster** [dauxio/daux.io#183]
**To Reproduce**

1. all-new install from docker, no config.json
2. create `docs/` directory (in tmpfs, in my case) with non-asci charactors (e.g. Chinese 汉字)
3. run `docker run --rm -it -w /build -v "$PWD":/build daux/daux.io daux generate`
4. daux generate wrong file name of html, it just skip all non-asci char in file name

**Expected behavior**

generate directory and html file with Chinese charactors

**Screenshots**

![image](https://user-images.githubusercontent.com/7328584/71313551-26dcce80-2475-11ea-80f6-a1777ced660e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - PHP_VERSION=7.3.12

**Additional context**

Is any more config needed to generate from non-asci file ? 

There is a official example [你好世界.html](https://daux.io/Examples/%E4%BD%A0%E5%A5%BD%E4%B8%96%E7%95%8C.html) include Chinese charactor, how to make it?

Anyway, charactors in md file converted as expected.

**Comment by onigoetz** [comment]
Hello, thanks for the report, I noticed the same with my most recent changes, I will look into it.

**Comment by onigoetz** [comment]
The issue was introduced by fixing #86 in 0.9.2 so in the meantime, you can use version 0.9.1.

I'm working on a fix.

**Comment by onigoetz** [comment]
The fixes discussed in this issue are available in [version 0.12](https://github.com/dauxio/daux.io/releases/tag/0.12.0)
