### ISSUE TITLE
Menu error on HTTPS access

### ISSUE THREAD

**Issue by NothingCtrl** [dauxio/daux.io#184]
**Describe the bug**
* On Desktop: The left menu error (overlap) when access site using https connection
* On Mobile: Top-right click not showing the menu

**To Reproduce**

0. Create site with https support
1. Go to site
2. Click on menu left
3. See error

**Expected behavior**
The menu working normatly

**Screenshots**
HTTPS
![daux_menu_error_https](https://user-images.githubusercontent.com/5380820/72242789-d6dccc00-361c-11ea-9b52-2e080c58a1b8.png)
*** 
HTTP
![daux_menu_normal_http](https://user-images.githubusercontent.com/5380820/72242795-d9d7bc80-361c-11ea-9c68-7e95faf1c11f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 + Windows
 - Browser: Google Chrome 79.0.3945.79, Firefox 72.0.4 (64-bit)

**Smartphone (please complete the following information):**
 - Device: MiMax3
 - OS: Android 9
 - Browser: Chrome
 - Version: 76.0.3945.116

**Comment by NothingCtrl** [comment]
Update, after playing with config file, the error only happen on default theme `daux-blue`

**Comment by NothingCtrl** [comment]
Update, theme still error on mobile device

**Comment by moritzfl** [comment]
I can confirm that this is a problem on iOS as well.

**Comment by onigoetz** [comment]
Thanks for the report, this is fixed on the master branch and will be in the next release

**Comment by onigoetz** [comment]
Fix available in version [0.12.1](https://github.com/dauxio/daux.io/releases/tag/0.12.1)
