### ISSUE TITLE
Fatal error while generating html files from markdown

### ISSUE THREAD

**Issue by proggeler** [dauxio/daux.io#185]
**Describe the bug**
TypeError: Return value of Todaymade\Daux\Tree\Directory::getIndexPage() must be an instance of Todaymade\Daux\Tree\Content or null, instance of Todaymade\Daux\Tree\Raw returned in /home/proggeler/dev/rtfm/vendor/daux/daux.io/libs/Tree/Directory.php on line 145

**To Reproduce**
1. folder containing markdown files
2. vendor/bin/daux generate --source=src

**Expected behavior**
html files will be generated!

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Comment by onigoetz** [comment]
Fixed by #186

**Comment by onigoetz** [comment]
Released in https://github.com/dauxio/daux.io/releases/tag/0.12.1
