### ISSUE TITLE
Running repo on shared hoster

### ISSUE THREAD

**Issue by kc853** [dauxio/daux.io#187]
Hi, just copied the repo content to my shared hoster (php 7.2). First run gave me an error /vendor is missing. I managed to get the vendor folder from elsewhere (composer on another machine) an placed it beside the repo files. Now I see the folder structure of the docs, but "An error occured The Page you requested is yet to be made. Try again later.", and no file is rendered. Could you please point me to the right direction?

Regards.

**Comment by onigoetz** [comment]
Hello, I don't recommend using daux directly from a hosting environment, I would generate the static files from the markdown `daux generate` and publish the resulting html files.

Now to your specific questions, the error you get is the standard 404 from Daux. This can mean a few things, maybe the URL rewrite hasn't been setup correctly ? 
On shared hosts, the PHP Server generally runs on Apache and would thus need an `.htaccess` file
We provide a default .htaccess with Daux : https://github.com/dauxio/daux.io/blob/master/.htaccess can you check if that is setup properly on your host ?

**Comment by kc853** [comment]
Thank you for the response. The .htaccess seems to be OK. Unfortunately I dont't find the time to do more research on this. Closing this support request for now.
