### ISSUE TITLE
Deprecated: array_key_exists():

### ISSUE THREAD

**Issue by Srki94** [dauxio/daux.io#189]
Hi, 
There's an issue with PHP 7.4.2 :

> PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\Users\srki9\AppData\Roaming\Composer\vendor\daux\daux.io\libs\BaseConfig.php on line 18
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\Users\srki9\Desktop\daux.io-master\daux.io-master\templates\layout\00_layout.php on line 8
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\Users\srki9\Desktop\daux.io-master\daux.io-master\templates\layout\00_layout.php on line 16
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\Users\srki9\Desktop\daux.io-master\daux.io-master\templates\layout\00_layout.php on line 53
PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in C:\Users\srki9\AppData\Roaming\Composer\vendor\daux\daux.io\libs\BaseConfig.php on line 18

The error reports back various lines in BaseConfig.php and 00_layout.php

Is there a quick fix for this, as it affects the generated pages - they're filled with the same error? 

To reproduce : 
Run daux generate on this version of PHP.

**Comment by onigoetz** [comment]
Thanks for the report, this is fixed on the master branch and will be in the next release

**Comment by onigoetz** [comment]
Available in version [0.12.1](https://github.com/dauxio/daux.io/releases/tag/0.12.1)
