### ISSUE TITLE
: don't work in Front Matter title

### ISSUE THREAD

**Issue by gerundt** [dauxio/daux.io#19]
I try today to use a `:` char in the Front Matter title and got a HTTP 500 error.

```
---
title: Foo: Bar Test
---
```

**Comment by onigoetz** [comment]
Hi,
this is invalid YAML

try with :
```
title: "Foo: Bar Test"
```

You can use http://www.yamllint.com/ to test your front matter if you have a doubt

**Comment by gerundt** [comment]
Thanks. using `"` works! 👍
