### ISSUE TITLE
Search doesn't work in Chrome for static daux websites

### ISSUE THREAD

**Issue by MatthewJamesHanson** [dauxio/daux.io#198]
**Describe the bug**
Search feature does not work in Chrome for static sites due to fetch API failing ni Chrome browser due to CORS issue. Error messages below:

index.js:44 Fetch API cannot load file:///C:/Users/.../daux_search_index.json. URL scheme must be "http" or "https" for CORS request.
value @ index.js:44
(anonymous) @ index.js:84

and

index.js:44 Uncaught (in promise) TypeError: Failed to fetch
    at e.value (index.js:44)
    at HTMLInputElement.<anonymous> (index.js:84)
value @ index.js:44
(anonymous) @ index.js:84
Promise.then (async)
value @ index.js:48
(anonymous) @ index.js:84

**To Reproduce**
1. Generate a daux website using the following (relevant) config.json settings:
{
    "format": "html",
    "html": {
        "search": true,
    }
}

**Expected behavior**
Search should work, just as it does in hosted sites, for Chrome.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
My team decide to use daux to generate static sites for a program we are making. The clients will not necessarily have access to the internet while using the program, hence static files were chosen as the best option. As a result, search doesn't work.

**Comment by onigoetz** [comment]
Hello, I will have a look to transform search into jsonp so that it works locally, I didn't think purely static local websites were in use anymore. However since the rest of Daux already works, adding search seems a reasonable addition

**Comment by onigoetz** [comment]
The latest changes were released in version [0.13.0](https://github.com/dauxio/daux.io/releases/tag/0.13.0)

**Comment by MatthewJamesHanson** [comment]
Thanks for the fixes. 

I'm not sure whether this is an additional issue (since my original issue _specifically_ mentioned Chrome) or whether related to this issue, so let me know if this should be a new issue or whether this comment is sufficient.

**New Issue**
**Describe the bug**
When a using a daux website in IE and Windows, doing a search launches explorer.exe on the system and does not provide a search result.

**To Reproduce**
Steps to reproduce the behavior:
Open a daux website in Internet Explorer
Search for a keyword
Explorer.exe launches in the foreground

**Expected behavior**
Search should work, just as it does for Chrome.

**Desktop (please complete the following information):**
OS: Windows
Browser: Internet explorer 11.719.18362.0

**Additional information**
Not tested on other systems

**Comment by onigoetz** [comment]
wow, that is weird indeed.
I will have a look at this specific case.

**Comment by MatthewJamesHanson** [comment]
As per https://github.com/dauxio/daux.io/releases/tag/0.13.0

this is closed.
