### ISSUE TITLE
Thank you & a new documentation realized with daux

### ISSUE THREAD

**Issue by dsentker** [dauxio/daux.io#2]
Great Tool, thank you for your effort to move it to an "active" repository maintainer.
It would be a good idea to explain that the "old" repository is not maintained anymore.

By the way - can you add my [documentation for DoctrineWatcher](https://dsentker.github.io/WatcherDocumentation/) realized with daux in the [demos](https://dauxio.github.io/Getting_Started.html#page_Demos) section?

**Comment by onigoetz** [comment]
Hi, thanks.

I have to admit I'm not the most "active" maintainer, but I hope I can be present enough :)
