### ISSUE TITLE
Custom header for locale index page when using the multilanguage setup

### ISSUE THREAD

**Issue by jidckii** [dauxio/daux.io#200]
**Is your feature request related to a problem? Please describe.**
Now the home page doesn't look pretty, because it basically just reflects the prefix.
I would like to be able to redefine this somehow

Example:  
![](https://i.imgur.com/6ams8YQ.png)

And if you do not create index in the subdirectory, then when switching to /ru, it will be 403
![](https://i.imgur.com/0w1Cv66.png)

my current structure 
![](https://i.imgur.com/XdMccXj.png)

**Describe the solution you'd like**
Add the ability to set a custom header for  locale index page when using the multilanguage setup

**Comment by onigoetz** [comment]
Hello,
can you try adding

```
---
title: Custom english title
---
```

at the very beginning of `en/00_index.md`

**Comment by jidckii** [comment]
Thank you!
