### ISSUE TITLE
Taking too long loading HTML

### ISSUE THREAD

**Issue by Davegb** [dauxio/daux.io#202]
**Describe the bug**
When I open the generated HTML content, it takes like 2 minutes like this before loading the whole thing on Chrome or Brave:

![image](https://user-images.githubusercontent.com/12886612/79526697-7a2dea80-802b-11ea-89f5-a58cfe6e2726.png)

**To Reproduce**
1. Install daux (composer require daux/daux.io)
2. Run daux generate
3. Go to the folder where it's generated and open Getting_Started.html on Chrome or Brave
4. It happens when I go to any page.

**Expected behavior**
Should load the page in seconds.

 - OS: Windows 10
 - Browser: Tested with Chrome and Brave
 - Chrome version: 80.0.3987.163
 - Brave version: Version 1.3.118 Chromium: 80.0.3987.116

**Additional context**
I tried Firefox, IE 11 and Edge Chromium. Firefox and IE load pretty fast, almost instantly, while Edge Chromium also showed everything from the start, but it looks like it also takes a while to finish loading, I can tell due to the indicator. May be something with the Chromium engine.

**Comment by imsoftware** [comment]
@Davegb Do you see any errors in the inspector (right click > inspect) or hints about loading time?

**Comment by Davegb** [comment]
@imsoftware I inspected it, but I didn't find anything. However, I googled why would a CSS file take a lot of time to load and I found the solution. In the last part of the HTML there is a script related to Google Analytics, it has a link: "//www.google-analytics.com/analytics.js". I put "https:" at the beginning of the link, turning it into "https://www.google-analytics.com/analytics.js" and it's fast now. However, since this is autogenerated code, I can't do this for every HTML each time it's generated. Is there a way to fix this?

**Comment by imsoftware** [comment]
Look at https://github.com/dauxio/daux.io/blob/master/templates/partials/google_analytics.php

**Comment by onigoetz** [comment]
Hi, I had a look at  #194 and there was indeed a bug with the check for Google Analytics.
I will also have a look and update the Google Analytics loading script as needed, it should be blocking to load the page.

**Comment by onigoetz** [comment]
The latest changes were released in version [0.13.0](https://github.com/dauxio/daux.io/releases/tag/0.13.0)
