### ISSUE TITLE
Display images inline

### ISSUE THREAD

**Issue by jtrav09** [dauxio/daux.io#204]
Greetings,
I am not super familiar with markdown, but I was previously using a different markdown application to track release notes for an internal application. I used image "tags" to add images via image references to keep the markdown cleaner for "Fix", "New", "Change" etc. These were displayed inline essentially serving as bullets.

![image](https://user-images.githubusercontent.com/64424551/80389085-a7269c80-8878-11ea-90bc-785c0bdd9939.png)

The release notes were becoming unmanageable in previous said viewer so I began looking for something else and stumbled across this app. 

I copied all of the markdown files over but I can not get the images to display inline.

Our application is proprietary so I can't post exact screenshots, but here is a mockup of what is occurring.

![image](https://user-images.githubusercontent.com/64424551/80389434-13a19b80-8879-11ea-9763-89307006cc49.png)

It seems that I am missing something. Even when writing something like a user manual/guide, there are times where I would want to include images inline with text, for example when showing an icon that a user should click,. I don't always want the image on its own line, but a carriage return always allows me to do this.

Can you point me to where I can fix this?

**Comment by onigoetz** [comment]
Hello, this is most probably related to the default CSS embedded with Daux.
I will have a look tonight if there is something I can do for you.

In the meantime, if you are working with the `:latest` docker image or with `dev-master` from packagist, you can try to add a `style.css` file at the root of your documentation to tweak the styles yourself (it's a new feature that is yet unreleased)

**Comment by onigoetz** [comment]
Hi, this has been released in [Version 0.14.0](https://github.com/dauxio/daux.io/releases/tag/0.14.0)
