### ISSUE TITLE
global.json defines "image" property, so you can't unset it

### ISSUE THREAD

**Issue by Faldrian** [dauxio/daux.io#205]
**Describe the bug**
You can't generate a documentation with the default theme and not have an "HomepageImage" on the global landing page. 

**To Reproduce**
1. create a new project with an index.md and another Markdown file (so generation works)
2. Create a global.json file next to it and define title and author. No "image" is defined.
3. The generated documentation will habe an image with «src=""» embedded, resulting in alt-text shown.

**Expected behavior**
If "image" would not be defined, you can leave it blank and the template logic of "hasImage" would work.

**Additional context**
This is a minor thing... but causes me to use my own template or a blank image, which is not ideal. ^^

**Comment by onigoetz** [comment]
Hi, I made a fix in the master branch, you can try to take the project from dev-master or the latest docker image, I'll release the fix soon

**Comment by onigoetz** [comment]
Hi, this has been released in [Version 0.14.0](https://github.com/dauxio/daux.io/releases/tag/0.14.0)
