### ISSUE TITLE
Sections with the same name result in the same ID for every div

### ISSUE THREAD

**Issue by Davegb** [dauxio/daux.io#209]
**Describe the bug**
If I create a page with several subsections with the same name, for example Section, the first one has an id="page_Section" and the second one has an id="page_Section-2", but the subsequent sections also have an id="page_Section-2".

**To Reproduce**
1. Create a md file with several sections called Section or whatever.
2. Serve.
3. Check the source code of the page. You'll see every section called "page_Section-2" except for the first one.

**Expected behavior**
It shouldn't stop on 2, but keep incrementing the number: page_Section-3, page_Section-4, etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/12886612/83704036-9e8f5780-a5d6-11ea-8b14-5350aa2dadab.png)

**Desktop (please complete the following information):**
 - OS: Pop OS! 20.04
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by onigoetz** [comment]
Oh, I was sure this was covered in tests, I'll look into it

**Comment by onigoetz** [comment]
Hi, this has been released in [Version 0.14.0](https://github.com/dauxio/daux.io/releases/tag/0.14.0)
