### ISSUE TITLE
tipuesearch shows german umlauts wrong

### ISSUE THREAD

**Issue by gerundt** [dauxio/daux.io#21]
In the old repro is a bug about the search and German umlauts:
https://github.com/justinwalsh/daux.io/issues/463

This is still a problem!

**Comment by onigoetz** [comment]
oh sorry, I was sure this was fixed, will have a look tonight

**Comment by onigoetz** [comment]
Hi @gerundt I was able to fix it.

Can you confirm it works and I'll release it ?

**Comment by gerundt** [comment]
The search show me now correct German umlauts! 👍 

Thank you!
