### ISSUE TITLE
Support for override configuration on git submodule

### ISSUE THREAD

**Issue by geraldolsribeiro** [dauxio/daux.io#220]
I want to edit pages located on several git repositories.

My global documentation is composed of several git submodules and I appreciate using the `edit_on` feature pointing to the specific git submodule repository.

I try to write a config.json file inside the folder of submodule changing the `basename` entry, but without success to link to the correct repository.

**Comment by onigoetz** [comment]
Hello,
currently there is no way to set a per-directory configuration, I do plan to have that in the future though, exactly as you describe it : through a config.json in the directory

**Comment by onigoetz** [comment]
Keeping this in mind but closing the task for now
