### ISSUE TITLE
Add content containers (markdown extension)

### ISSUE THREAD

**Issue by aedart** [dauxio/daux.io#224]
It would be really nice being able to use "content containers", similar to those available in [vuepress](https://vuepress.vuejs.org/guide/markdown.html#custom-containers). Authors are then able to highlight specific content, and thereby increasing the chance that readers are made aware of specific information, e.g. warnings or tips.

I'm pretty sure that this isn't a part of any markdown standard. Yet I do not believe that it will decrease the readability of the source markdown file, provided that a similar easy syntax is used, as that from vuepress.

**Comment by onigoetz** [comment]
Hi, this is a very interesting feature, I'll have a look if such an extension exists.
If not I'll try to figure out how to implement it.

Can't give a deadline though

**Comment by Jako** [comment]
It is part of the python markdown standard extensions: https://python-markdown.github.io/extensions/admonition/ and it would be great, if this could be included into daux too.

**Comment by onigoetz** [comment]
I just implemented this feature in the master branch. 

Works for both HTML and Confluence rendering

* https://daux.io/Features/Admonition.html
* https://dauxio.atlassian.net/wiki/spaces/DOC/pages/2849899333/Admonition

I will add some tests and release it soon after

**Comment by onigoetz** [comment]
Released in 0.20.2 : https://github.com/dauxio/daux.io/releases/tag/0.20.2
