### ISSUE TITLE
Quotation mark in heading truncates TOC

### ISSUE THREAD

**Issue by JKingweb** [dauxio/daux.io#240]
**Describe the bug**
If a page contains a table of contents and a section heading contains either U+0022 QUOTATION MARK or U+0027 APOSTROPHE, the heading in the TOC will be truncated prior to the character in question. This is a regression introduced in version 0.14; prior version did not exhibit this behaviour.

**To Reproduce**
1. Write a document like the following:

``` 
[TOC]

# Daux's bug
```

2. Generate documentation
3. Note that TOC will read `Daux` rather than `Daux's bug`

**Comment by onigoetz** [comment]
Hi, I published a fix in 0.15.1
