### ISSUE TITLE
Timestamp resources when generating docs

### ISSUE THREAD

**Issue by gacekssj4** [dauxio/daux.io#246]
It's quite common these days to use browser side caching. Not everyone know when to clear caches if page changed.

On my docs I changed styles completely and uploaded data to server. I know i have to press Ctrl+F5 on browser, but most users do not. Or know, but do not know when site changed.

Would be great idea (may be in .config) to allow to add timestamp for resources like images and css/js.

theme-blue.css?t={generationtimestamp}

That way, we would be able to use caching and spare users trouble for wrong display.

I probably will solve this in preprocessor for now.

**Comment by onigoetz** [comment]
Cool idea, I will think about how this could be implemented.

Although shouldn't apache/nginx give Etags for static assets in this case?

**Comment by gacekssj4** [comment]
@onigoetz Not sure if I have control over this on shared hosting. Do I?
From what Apache docs say I can set it from .htaccess level. Would have to test it. 

My server says

```
HTTP/2 200 OK
server: nginx
date: Tue, 16 Feb 2021 15:51:39 GMT
content-type: text/css
vary: Accept-Encoding
last-modified: Tue, 16 Feb 2021 15:32:20 GMT
etag: W/"312385-598a-5bb75cee7a45b"
content-encoding: br
X-Firefox-Spdy: h2
```
But `ctrl+f5` was only way to refresh. So maybe does not work on Firefox? No idea

**Comment by gacekssj4** [comment]
@onigoetz I think it could be implemented in `templates/layout/00-layout.php` I will try to do so.

**Comment by gacekssj4** [comment]
@onigoetz I think that would be great idea now.
After i posted headers i returned to my docs site. Even after i `ctrl+f5` flushed cache, my browser somehow did not remove cache and returned old CSS. Cache in browser is sometimes persistent as hell. Change of link always helps better than headers.

I temporary solved it likes this
```
<?php foreach ($config->getTheme()->getJS() as $js) { ?>
        <script src="<?= $js.'?t='.time(); ?>"></script>
    <?php } ?>
```
for and CSS/JS. Skipped fonts for now.

**Comment by onigoetz** [comment]
Closing this task as I won't have time to implementing this.
Although ultimately I think this comes down to the web server's configuration
