### ISSUE TITLE
Error in $PATH : no daux command

### ISSUE THREAD

**Issue by ItsWidee** [dauxio/daux.io#247]
Hello,

After doing the command `composer global daux/daux.io` on the web-server terminal, the `daux` command doesn't exist. I add it to $PATH, but the file `~/.composer/vendor/bin` doesn't exist.

Do I need to add another file to $PATH ?

**Comment by onigoetz** [comment]
Hello, 

this is probably related to your composer configuration, 

running `composer config --list --global` should give you an idea of where those files have been installed and what value to add to $PATH
