### ISSUE TITLE
Impossible to load Daux, missing vendor/

### ISSUE THREAD

**Issue by TheGuardianWolf** [dauxio/daux.io#25]
Hello,

I've used one of the old versions of Daux for quite some time, but when my hosting server got upgraded to PHP7, this stopped working.

I downloaded a new version of Daux and now I am getting this error as you can see on the site:
http://files.ultimogroup.co.nz/competenz/

I don't really know what this means, I have the docs in the docs folder as before, but it doesn't seem to be serving them like it used to.

**Comment by MasterOdin** [comment]
Did you use composer to install it (or install the dependencies of Daux if you downloaded it from the repo).

**Comment by TheGuardianWolf** [comment]
This is currently hosted on an apache server, I followed the instructions given on the readme here:

https://github.com/dauxio/daux.io#run-on-a-server

I'm guessing the dependencies need to be downloaded separately then?

**Comment by TheGuardianWolf** [comment]
Okay I just used docker to load daux and generate a static site, I'm still getting PHP errors.

```
Warning: Illegal string offset 'fonts' in /daux/templates/layout/00_layout.php on line 30 Warning: Invalid argument supplied for foreach() in /daux/templates/layout/00_layout.php on line 30 Warning: Illegal string offset 'css' in /daux/templates/layout/00_layout.php on line 35 Warning: Invalid argument supplied for foreach() in /daux/templates/layout/00_layout.php on line 35 
```

**Comment by Torsten-K** [comment]
Very similar here. It runs on my webhoster’s server, but not on my local machine (both Apache 2.4 and PHP 7.1). On my PC, the following error message appears (I left out the full path):

Fatal error: Uncaught Exception: Impossible to load Daux, missing vendor/ in […]/daux/libs/bootstrap.php:14 Stack trace: #0 […]/daux/libs/bootstrap.php(17): loadApp() #1 […]/daux/index.php(78): require_once('/home/torstosau...') #2 {main} thrown in […]/daux/libs/bootstrap.php on line 14

**Comment by onigoetz** [comment]
The `missing vendor/` means that you have to do `composer install` all dependencies aren't included as they were before.

**Comment by Torsten-K** [comment]
Thanks, @onigoetz, it works now.

**Comment by tonypartridge** [comment]
Can we close this then?

**Comment by onigoetz** [comment]
yes
