### ISSUE TITLE
Image with numeric names lose names.

### ISSUE THREAD

**Issue by seigieu** [dauxio/daux.io#26]
I noticed a problem. When I have numeric image name ( 123.jpg ) i get following output:
```
daux generate
Copying Static assets ...                            [  OK  ]
Generating ...
- index.html                                         [  OK  ]
- Start/index.html                                   [  OK  ]
- Examples/index.html                                [  OK  ]
- image/.jpg                                         [  OK  ]
```
When filename is non numeric it works fine.

**Comment by onigoetz** [comment]
To be honest, I didn't think of this use case :/ I'll have a look to see how it can be managed to not remove numbers in front of static files
