### ISSUE TITLE
Confluence no longer accepts username/pw Basic Authentication

### ISSUE THREAD

**Issue by KoenDG** [dauxio/daux.io#263]
**Describe the bug**
Ran into this recently. Username/pw login for Confluence no longer works.

See here: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

The deprecation and disabling has been going since 2019 and seems to be completed.

**To Reproduce**
If you have an existing project uploading to confluence with username/pw, it should not work for anyone, at all.

**Expected behavior**
Have some way to provide other means of authenticating with Confluence.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Daux version: 0.15.1

It just doesn't work anymore and it seems a switch to API tokens will be needed.
I went and checked the source code, seems like the expectation of username/pw is currently hardcoded: https://github.com/dauxio/daux.io/blob/master/libs/Format/Confluence/Generator.php#L37

So this ticket is basically here to signal the broken functionality and request a fix, if possible.

EDIT: It appears to show up only when using empty username/pw combo, look like I wasn't paying attention.

So, upload seems to still work. Yet, deprecation is a fact. What to do?

**Comment by onigoetz** [comment]
Hello,

Thanks for the heads up, I mostly use the confluence upload on a hosted instance so I might have missed it.

According to [the documentation](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/#APItokens-UseanAPItoken), you can use the token on curl with `--user email:token` which means that it's still using a form of basic auth. And you can use your email as the username and a token as a password.

I updated the documentation about this; you can do the following in your case

```json
{
    "confluence": {
        "base_url": "http://my_confluence_server.com/",
        "user": "my_username",
        "pass": "my_token"
    }
}
