### ISSUE TITLE
The template "theme::home" could not be found at "templates/home.php"

### ISSUE THREAD

**Issue by LorenzoTuri** [dauxio/daux.io#266]
After installing it globally, launching the command generate occurs in this error (see below for the full trace (-vvv))
The server runs Ubuntu 20.04.1

daux installed with "composer require global daux/daux.io"

Then I've created the source and destination folder, added in the source a few demo *.md files (index.md and index2.md, config.json), and run generate with "daux generate -s documentor/guides -d public/documentor/guides -vvv"

The command start executing, but stops before the creation of the "theme" folder in the destination path.

The config.json is a basic one:
{
    "title": "Documentation",
    "tagline": "Guides ...",
    "author": "Lorenzo Turi",
    "format": "html",
    "html": {
        "theme": "daux-navy" 
    }
}

**Additional context**
$  daux generate -s documentor/guides -d public/documentor/guides -vvv --no-cache
Copying Static assets ...
[  OK  ]
Generating ...
- index.html
Using cache dir '/tmp/dauxio/'
Cache disabled, generating...
Running conversion
Starting Template engine with basedir 'templates' and theme folder 'templates'.
Rendering template 'theme::home'
[ FAIL ]

In Template.php line 155:

  [LogicException]
  The template "theme::home" could not be found at "templates/home.php".

Exception trace:
  at /root/.config/composer/vendor/league/plates/src/Template/Template.php:155
 League\Plates\Template\Template->render() at /root/.config/composer/vendor/league/plates/src/Engine.php:277
 League\Plates\Engine->render() at /root/.config/composer/vendor/daux/daux.io/libs/Format/HTML/Template.php:76
 Todaymade\Daux\Format\HTML\Template->render() at /root/.config/composer/vendor/daux/daux.io/libs/Format/HTML/ContentPage.php:124
 Todaymade\Daux\Format\HTML\ContentPage->generatePage() at /root/.config/composer/vendor/daux/daux.io/libs/Format/Base/SimplePage.php:20
 Todaymade\Daux\Format\Base\SimplePage->getContent() at /root/.config/composer/vendor/daux/daux.io/libs/Format/HTML/Generator.php:179
 Todaymade\Daux\Format\HTML\Generator->Todaymade\Daux\Format\HTML\{closure}() at /root/.config/composer/vendor/daux/daux.io/libs/Console/RunAction.php:26
 Todaymade\Daux\Format\HTML\Generator->runAction() at /root/.config/composer/vendor/daux/daux.io/libs/Format/HTML/Generator.php:188
 Todaymade\Daux\Format\HTML\Generator->generateRecursive() at /root/.config/composer/vendor/daux/daux.io/libs/Format/HTML/Generator.php:70
 Todaymade\Daux\Format\HTML\Generator->generateAll() at /root/.config/composer/vendor/daux/daux.io/libs/Console/Generate.php:73
 Todaymade\Daux\Console\Generate->execute() at /root/.config/composer/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /root/.config/composer/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /root/.config/composer/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /root/.config/composer/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /root/.config/composer/vendor/daux/daux.io/bin/daux:71

generate [-c|--configuration CONFIGURATION] [-s|--source SOURCE] [-p|--processor PROCESSOR] [--no-cache] [-t|--themes THEMES] [--value VALUE] [-f|--format FORMAT] [--delete] [-d|--destination DESTINATION]

**Comment by Gerhard-Kanzler** [comment]
The problem is: you have a "templates" folder in your root! maybe you need a config.json to override the templates path

**Comment by LorenzoTuri** [comment]
Nice, it's working, conflicted with the symfony templates folder, thank you
