### ISSUE TITLE
Autocomplete for search

### ISSUE THREAD

**Issue by brusch** [dauxio/daux.io#28]
It would be pretty handy to have some kind of autocomplete with which you can jump directly to the desired page in the search, without opening the search results modal. 

What do you think?

**Comment by onigoetz** [comment]
Nice idea, I'll consider it when working on the Search feature again. I plan to make some improvements on the search library.

**Comment by celbasi** [comment]
this would be nice too!

**Comment by onigoetz** [comment]
I implemented using flexsearch as a library to have more accurate results. I will not implement autocomplete for the moment however
