### ISSUE TITLE
Code does not float

### ISSUE THREAD

**Issue by acnimda** [dauxio/daux.io#283]
Code blocks does not float to the right, while enabled in `config.json`

**Steps to reproduce the behaviour:**
1. create a `config.json`
2. added in `config.json`
```js
"html": {
        "toggle_code": true,
        "float": true,
        "auto_toc": true,
        "theme": "daux-green",
        "breadcrumbs": true,
        "breadcrumb_separator": "Chevrons",
        "date_modified": true,
``` 
3. run `daux generate`

**Expected behavior:**
Expect code blocks on the right. Not integrated in content.

**version**
- Version daux/daux.io 0.16.2
- PHP 8.0.10

**Additional context**
It does not matter if I set  ` "toggle_code": true,` or `"float": true,` to `true` or `false`. Code blocks will not float.

**Comment by onigoetz** [comment]
Hello, I removed the feature quite a while ago : https://github.com/dauxio/daux.io/commit/ef496e9381e0dee76d8fe729bb0b18a06ad8f5e1

This is the commit right before this removal : https://github.com/dauxio/daux.io/tree/ac6e71030bb82dda5a1bd6b2fe8c3e4f8032949e you can extract the code and create a custom theme

**Comment by onigoetz** [comment]
I have a question though, did you find this reference in a documentation somewhere ?
