### ISSUE TITLE
Javascript error "FlexSearch is not a constructor"

### ISSUE THREAD

**Issue by axelhahn** [dauxio/daux.io#287]
**Describe the bug**
In a build site - and in the daux.io website too - the search does not work

**To Reproduce**
1. Go to [Daux.io - getting started](http://daux.io/Getting_Started.html)
2. Open Developer tools F12 - tab "console"
3. Type something in search field on the top left ... i.e. hello
4. See error in console
Uncaught (in promise) TypeError: FlexSearch is not a constructor
    loadingPromise index.js:57
    promise callback*value index.js:56
    value index.js:92
    value index.js:90
    search index.js:155
    <anonymous> Getting_Started.html:368

**Expected behavior**
I want to get a search result or a message if there is no hit.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10, Manjaro Linux
 - Browser Fierfox 95, MS Edge 96

**Additional context**
There is mo missing js file while loading the page. Maybe a class was was renamed?
The described behavior is independent from browser and OS.

In index.js ... 
```js
...
            this.loadingPromise = new Promise(resolve => {
                window.load_search_index = data => resolve(data);
            }).then(json => {
                this.searchIndex = new FlexSearch({   <<<< script fails here
                    doc: {
                        id: "url",
                        field: ["title", "text", "tags"]
                    }
                });
...
```

**Comment by onigoetz** [comment]
oh my that's bad, I'll have a look right now.
There are no frontend tests setup for now but I'll try to add them as well to avoid future issues

**Comment by onigoetz** [comment]
Fixed in https://github.com/dauxio/daux.io/releases/tag/0.17.2

**Comment by axelhahn** [comment]
@onigoetz THX for fixing it so fast!
