### ISSUE TITLE
SEO: one H1 per page

### ISSUE THREAD

**Issue by axelhahn** [dauxio/daux.io#289]
**Is your feature request related to a problem? Please describe.**
A good html page should have just one H1 header.
Also a good markdown should have just one H1 header. See https://github.com/updownpress/markdown-lint/blob/master/rules/025-single-h1.md

The current default theme generates a H1 for the breadcrumb on top.
So ... If I set a single H1 in my md file I get 2 H1 in the rendered page ... one for the breadcrumb and one for my H1 header of the markdown content.

**Describe the solution you'd like**
The breadcrumb on top should be inside a nav tag .. and the links not inside a h1.
(Maybe the left navigation can be a nav tag instead of a div too)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by onigoetz** [comment]
Hi, the breadcrumb is meant to be the title of the page, that's why it's the H1 and there should be no h1 inside the markdown.

Apart from that, It seems that it's not mandatory to have only one h1 per page : https://www.searchenginejournal.com/h1-headings-for-google/406720/

**Comment by axelhahn** [comment]
Hi, 

for me is clear that the title in navigation and breadcrumb comes from the filename. The auto generation of the navigation tree is a big plus of Daux - a few other generators I had a look to expect that I create the menu tree in the config file.

The Markdown linter in VS Code wants exactly one H1 otherwise it is unhappy. If possible I search for a solution to have a well formed md, a good md rendering in Github (or Gitlab) and a good rendered static html page.

It has definitively lower priority. Maybe somewhen I have a look, how to create my own output theme to put the breadcrumb into a nav tag. Thanks for your additional link!

Axel
