### ISSUE TITLE
Single-page HTML export fails with incompatible getLinkRenderer

### ISSUE THREAD

**Issue by gwittenburg** [dauxio/daux.io#291]
**Describe the bug**
Single-page HTML export fails with the following error:

`Fatal error: Declaration of Todaymade\Daux\Format\HTMLFile\ContentTypes\Markdown\CommonMarkConverter::getLinkRenderer(League\CommonMark\Environment\Environment $environment) must be compatible with Todaymade\Daux\ContentTypes\Markdown\CommonMarkConverter::getLinkRenderer(Todaymade\Daux\Config $config) in /daux/libs/Format/HTMLFile/ContentTypes/Markdown/CommonMarkConverter.php on line 7`

Regular (multi-page) HTML works fine for the same project.

**To Reproduce**
Run the following command with the currently latest (v0.17.2) Docker image:
`docker run -it -w /build -v "$PWD":/build --rm daux/daux.io daux generate --format=html-file`

**Expected behavior**
Above command should generate single-page HTML output, given that multi-page works fine.

**Screenshots**
n/a

**Desktop (please complete the following information):**
Ubuntu 21.10

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by onigoetz** [comment]
Hi, I fixed the output of single-page in the master branch, it mostly works but anchors within pages might link incorrect to one another. I'll look into it next.

**Comment by gwittenburg** [comment]
Thanks so much, Stéphane!

**Comment by onigoetz** [comment]
Released in version [0.18.0](https://github.com/dauxio/daux.io/releases/tag/0.18.0)

**Comment by gwittenburg** [comment]
Thanks, Stéphane, much appreciated!

Could there be a minor packaging issue regarding main.min.css (see https://github.com/dauxio/daux.io/issues/294)?
