### ISSUE TITLE
Package is not showing up in Packagist

### ISSUE THREAD

**Issue by gubler** [dauxio/daux.io#3]
When I search for `dauxio` on Packagist I only get the original repo and my parsedown package. If I search with composer, I (as expected) get the same thing).

**Comment by onigoetz** [comment]
Hi,

I don't know why it doesn't come up in search, it's available by url : https://packagist.org/packages/daux/daux.io

**Comment by gubler** [comment]
The documentation in the README gives the install instructions as:

`composer global require dauxio/daux.io`

With the link you posted above, the command should be (which I have confirmed _does_ work):

`composer global require daux/daux.io`

As for why searching for `daux`, `dauxio`, or `daux.io` doesn't bring up the new project... ¯\_(ツ)_/¯

**Comment by gubler** [comment]
I _would_ also say that its a bit odd that the packagist entry is `daux/daux.io` but the GitHub project is `dauxio/daux.io`. Is it too late to change the packagist entry to match the GitHub project name?

**Comment by onigoetz** [comment]
Hi, the documentation is fixed now.

Actually, I would prefer if the organization could be "daux" instead of dauxio, but it's taken for the moment
