### ISSUE TITLE
Dark mode anyone?

### ISSUE THREAD

**Issue by Bockiii** [dauxio/daux.io#301]
**Is your feature request related to a problem? Please describe.**
The default theme burns my eyes, which may become a problem in later stages of life.

**Describe the solution you'd like**
Github-Dark-Mode-Style-Theme

**Describe alternatives you've considered**
Doing it myself, hindered mostly by my drastic incompetence and slight color blindness

**Additional context**
I would love for the default themes to be extended by a github-dark-mode-style theme. Because the documentation usually requires a lot of text read up close, the default colors are just way to aggressive for reading imho. I've already tried my hand and have gotten as far as changing the nav bar to gh-like colors, but when I noticed how much else was missing, I just gave up.

Thanks in advance!

**Comment by onigoetz** [comment]
Implemented in version [0.20.0](https://github.com/dauxio/daux.io/releases/tag/0.20.0)

**Comment by Bockiii** [comment]
Nice, will check it out later!
