### ISSUE TITLE
The "themes" option does not exist

### ISSUE THREAD

**Issue by Eric--** [dauxio/daux.io#31]
when I input  'daux serve', It come one error 'The "themes" option does not exist'. I also 
'daux generate' successful. when I put in nginx and php-fpm, It show 'array_key_exists() expects parameter 2 to be array', and style maybe lossed.

**Comment by onigoetz** [comment]
Hello,

the first error is my mistake, I'll be fixed in today's release

Do you have more details on the `array_key_exists expects parameter 2 to be array ` ?

**Comment by onigoetz** [comment]
the `themes option` issue has been fixed and released in 0.7.1

**Comment by Eric--** [comment]
@onigoetz  thank you for your help ! I have fixed two problems before.  I  execute 'rm -rf static' before ' daux generate', so it works fine.
