### ISSUE TITLE
Can't run daux from folder (not root directory)

### ISSUE THREAD

**Issue by gosteev** [dauxio/daux.io#32]
Hey. I try to run daux 0.6.0 from folder, but got this strange 404 response and inner page instead of intro:

![qwe](https://user-images.githubusercontent.com/6203574/33956541-80b4d494-e047-11e7-8566-3d750daeb7f5.png)

I tried to do set clean_urls to false and my .htaccess file is present, but result is the same.

The last 0.7.1 version gives additional errors:

![asd](https://user-images.githubusercontent.com/6203574/33956649-e393104e-e047-11e7-8947-541d9cf8a9d5.png)

**Comment by onigoetz** [comment]
Hello,

can you please try with the latest version ?

Also, are you running from a specific server ? or behind a reverse proxy ?

**Comment by gosteev** [comment]
hello. i bypassed issue, how exactly i can't remember.  it was local apache 2.4 server
