### ISSUE TITLE
DauxHelper.php line 424 failure on finding Pictures

### ISSUE THREAD

**Issue by wemasoe** [dauxio/daux.io#335]
The generation stops, when pictures are linked in the markdown file in base64 encoding. 

Failure Message:
`
In DauxHelper.php line 424:`
`
  Could not locate file 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACOElEQVQ4jZWTTUiUURSGn3
  O+0RknR0dzFMpM3FQjZakUYfYDLkJaF7QKF61qUZuWQdCqRauIlkFBtGkRSRC5yTD6kah0DMIcM8gRsi8d9fu9LeYHR1vUXd57z3vue+7zChuWeUsVI
  Z0oh4GO4vZXDGPEmZBO3PX3ZUPxbgyXEE4BLQhW4YAAmAeGUW5KN5ObBMwbjiPcAtIo+L6wlLdQhUQ8QNWAASCDclG6eV4WMK/pRHkIpBGYysa5/yxF
  JhsnYhl6di1zdiDH9pRbEpkCTksvH8VMUM0atzEMIfBlroYrd9r5losSsQz51YKLvr2/uTaUpSnplUTuUsP5CHm6UAaLXnn0YivzP6u5em6WxoTH9Xt
  tpHeucHSfTSYbpz9pl1yfZI3uCBZ9GJoBHE+Zmq0h3b7CQO8votUhx/bbHNyzRH+XzfjnWoJAsNQApDAcUQwdgCLgB8Kaq4TleYHrCXO5KIt2FZMzcf
  ygPHcFOiLrv9H1BcdTZn7EeDzaSGOdz+iHekbeCU/GGvADZfDQItFkWO4QQZjGEALqeoLjKvlVixsPWlE1OK4CsGBX0Zz0WF61aGrwKNZMKwEvgVwFj
  mLwA8H1FCm+2BhoTTk0JPxS9wWEUUV5jzCMKQCzrckhCIQgFIwBVUMy4XPigM3lM9+pry0LPCXGeCVIQvrTdJxXk3WIGLbEQlL1HjuaHdpaHGLRcDNI
  m1CWAo0VoBsgLBvMIFyQHkYqsgB/CRPFMPEPYVon8l9x/gOWi+cJUGNUhgAAAABJRU5ErkJggg=='
`

**Comment by onigoetz** [comment]
Hi, thanks for the report, I'll check and fix that.

**Comment by onigoetz** [comment]
Fixed in version [0.20.0](https://github.com/dauxio/daux.io/releases/tag/0.20.0)
