### ISSUE TITLE
How to activate "Code blocks" switcher from the official docs API?

### ISSUE THREAD

**Issue by Denis4yk** [dauxio/daux.io#34]
Is it possible to activate this buttons somewhere from the config?
<img width="222" alt="screen shot 2017-12-25 at 13 12 03" src="https://user-images.githubusercontent.com/15350325/34338867-917a75fe-e975-11e7-856b-b4a14ef0eb56.png">

**Comment by onigoetz** [comment]
Hello

to enable them you have to enable the `toggle_code` and `float` settings
- `toggle_code`: https://github.com/dauxio/daux.io/blob/master/docs/config.json#L17 (enabled by default)
- `float`: https://github.com/dauxio/daux.io/blob/master/docs/config.json#L20 (disabled by default)

The documentation sections about those are : 

- https://dauxio.github.io/Configuration/Html_export.html#page_Code-Floating
- https://dauxio.github.io/Configuration/Html_export.html#page_Toggling-Code-Blocks

**Comment by rmldsky** [comment]
Is there a way to set the default for this toggle in `config.json`?
