### ISSUE TITLE
Markdown and confluence collapsible support

### ISSUE THREAD

**Issue by seburdin** [dauxio/daux.io#349]
Would be useful to have a support for collapsible sections of documentation, both for github and confluence exports.

Thanks a lot.

**Comment by onigoetz** [comment]
I'm almost there ! 

https://dauxio.atlassian.net/wiki/spaces/DOC/pages/2850914305/Collapsible

It now works but I should add a condition to not convert within a code block.

since the code block should show how to use the feature, not the end result : https://daux.io/Features/Collapsible.html

**Comment by onigoetz** [comment]
Released in 0.21.0 https://github.com/dauxio/daux.io/releases/tag/0.21.0
