### ISSUE TITLE
Support ignoring nested subfolders.

### ISSUE THREAD

**Issue by bd82** [dauxio/daux.io#35]
Hello and thanks for daux 👍 

To the best of my understanding only one level of folders under the docs dir can be ignored.
This means that if I have a folder structure of:

- Docs
   * A
     - A1
     - A2

I cannot ignore just the A1 or the A2 folder.
(or maybe I am doing something wrong?)

Here are my docs folder and config for reference.
https://github.com/SAP/chevrotain/tree/f2136347a85b41c1bf3d8756e1d1a3a9e8cd125c/docs

Thanks.

**Comment by onigoetz** [comment]
Hello,

currently you can only specify a single folder name, not a path, so you would need to specify "src" as your ignored folder.

**Comment by bd82** [comment]
I reorganized my project structure to avoid this issue 😄
