### ISSUE TITLE
Possibility to automate creation of root page in confluence when ancestor_id only is provided

### ISSUE THREAD

**Issue by seburdin** [dauxio/daux.io#358]
**Is your feature request related to a problem? Please describe.**
When trying to push a new documentation tree under a common ancestor_id, if fails if the root page of this new documentation tree doen't pre-exist under the ancestor_id page 

**Describe the solution you'd like**
Have an option to automate  creation of this root page under the provided ancestor id even when it doesn't preexist

**Describe alternatives you've considered**
Create manually this root page, but it doesn't not scale and cope well  with my goal of automating migration do daux for a lot of repositories published under the same root.
Create an additional script in my documentation workflow/process that would create the required root page on eureka.

**Additional context**
Exception logs from https://github.com/dauxio/daux.io/blob/master/libs/Format/Confluence/Publisher.php#L125 : 
```
In Publisher.php line 124:  Could not find a page named 'BAD - XXX docs' b  
  ut found [''].
```

**Comment by onigoetz** [comment]
Added in 0.21.0 https://github.com/dauxio/daux.io/releases/tag/0.21.0
