### ISSUE TITLE
Confluence generation error on specific code section patterns

### ISSUE THREAD

**Issue by seburdin** [dauxio/daux.io#362]
**Describe the bug**
Generation of confluence content failing on specific code contents.

**To Reproduce**
1. create a md document containing code 
```
public class Interceptor {

   private String name;
   private Rule primary;
   private List<Rule> secondary;
}
```

2.Generate confluence report with daux version >= 0.21.0

3.Generation fails with following message: 
```
Content: 
 16 |    private List<rule> secondary;
 17 | }
>18 | ]]></rule></ac:plain-text-body></ac:structured-macro>
             ^
 19 | <p>Each <code>Rule</code> contains a <code>Conditions</code> object which comes with the following 3 flavors:</p>
 20 | <ac:structured-macro ac:name="code"><ac:parameter ac:name="language">java</ac:parameter><ac:plain-text-body><![CDATA[public class Rule {    [ FAIL ]
```

**Expected behavior**
Confluence page generated with code snippet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chrome]

**Comment by onigoetz** [comment]
Thanks for the report, I was able to reproduce and fix this issue : 

![image](https://user-images.githubusercontent.com/309594/212432622-ccc946c2-9118-4dc6-a8c4-969a7ce0d386.png)

**Comment by onigoetz** [comment]
Fixed in https://github.com/dauxio/daux.io/releases/tag/0.21.3
