### ISSUE TITLE
Disable (visible) permalinks for paragraph headers

### ISSUE THREAD

**Issue by ThePoetics** [dauxio/daux.io#371]
I updated/re-pulled my Daux installation today and now after making several edits my document headers (H1 through H3 are the ones I've tested) now all display the # symbol with a permalink to the section in question.

Is there a configuration option to disable the creation/display of these links? Other than a single page where a TOC may be beneficial the rest of the site pages are short enough that having permalinks is unnecessary, and having them displayed seems to be nonstandard behavior, but I haven't changed anything structurally about the configuration since uploading.

Here is the code which results in the attached page display:
```
## Culture

Seattle is home to a diverse and multifaceted culture...
```

![image](https://user-images.githubusercontent.com/87587068/222287885-08b247ac-fdb9-4ca0-be0b-445ff1941f9e.png)

**Comment by ThePoetics** [comment]
It seems to be an issue with my hosting provider. Closing as no longer an issue

**Comment by onigoetz** [comment]
Hello,
I've had this behaviour on a theme. The reason what that the permalink was added in a newer version of Daux, but the CSS of the theme was for a previous version of the theme.

You might want to copy the latest version of the Daux CSS and re-apply your theme on it.
