### ISSUE TITLE
handling of extension .mjs

### ISSUE THREAD

**Issue by axelhahn** [dauxio/daux.io#387]
**Describe the bug**
On a ssl enabled website with security header `x-content-type-options: nosniff` the javascript won't be loaded.
It is not a bug - it should be documented in the help pages.

**To Reproduce**
1. generate static pages
2. uplad to a ssl enabled website and htp response header  `x-content-type-options: nosniff`
3. open the doc pages in the browser
4. The browser console shows `The resource from “https://www.eaxemple.com/docs/themes/daux/js/main.mjs” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff).`

**Expected behavior**
The .mjs file can be interpreted as javascript.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Mozilla Firefox
 - Version 115.0.2

**Smartphone (please complete the following information):**
-

**Additional context**
-

**My solution:**
The extension .mjs seems to be introduced in on of the latest versions of Daux.

In the webserver config (apache httpd) I added the type
`AddType application/javascript .mjs`

(in .htaccess or vhost config or server config)

**Comment by onigoetz** [comment]
Hi, thanks for the feedback, I added a note in the documentation about this, I hope that will be enough.

Due to some external dependencies, I can't fall back to use `.js` on Daux.
I will have a look if anything else can be done
