### ISSUE TITLE
Not working a custom proccesor with Docker

### ISSUE THREAD

**Issue by 2ur1st** [dauxio/daux.io#397]
**Describe the bug**
Not working a custom proccesor with Docker image daux/daux.io
Not generated docs because of error `Class '\Todaymade\Daux\Extension\Processor' not found. We cannot use it as a Processor `

**To Reproduce**
1) **I have files structure like this**
<img width="889" alt="Screenshot 2023-09-16 at 12 21 07" src="https://github.com/dauxio/daux.io/assets/4361999/42df7367-0063-44f6-92c6-6375abf68e81">
2) Run command:

```
docker run --platform=linux/amd64 --rm -w /build -v ./public:/build daux/daux.io daux generate --processor=Processor --source=daux/docs --destination=docs
```

3) Got error
<img width="1309" alt="Screenshot 2023-09-16 at 12 34 20" src="https://github.com/dauxio/daux.io/assets/4361999/9de79ca7-4ede-441e-af70-e0cec89f0025">

**Expected behavior**
See var dump of Proccesor script

**Desktop (please complete the following information):**
 - Docker daux/daux.io

**Comment by 2ur1st** [comment]
**Resolve:**
Problem was from incorrect path, for my case working dir tree is
<img width="404" alt="Screenshot 2023-09-16 at 18 13 25" src="https://github.com/dauxio/daux.io/assets/4361999/d2c6c7f5-b7e7-4d7f-b4c1-902f481b7c00">

**Comment by onigoetz** [comment]
Hi, sorry I saw this too late, yes indeed I would have pointed to an incorrect path or a missing docker mount
