### ISSUE TITLE
Single-HTML and PDF outputs.

### ISSUE THREAD

**Issue by Serdaro** [dauxio/daux.io#4]
The generator is awesome, thanks a lot for the efforts. Is there any plan to have single-HTML and PDF formats to be output too?

**Comment by onigoetz** [comment]
Hello,
thanks :)

Yes, there are plans, the single-HTML output was added experimentally, but doesn't work currently.
And the PDF exports needs a good library, to do, which is hard to find.

I will try to continue the progress on this in the next weeks.

**Comment by onigoetz** [comment]
Hello, the Single HTML page output works again, do you want to try it out ?

**Comment by Serdaro** [comment]
Sure @onigoetz , should I download the current repo?

**Comment by onigoetz** [comment]
it's best to download with

```
composer global require daux/daux.io
```

**Comment by Serdaro** [comment]
@onigoetz , okay. First time I did that it was a warning which I don't remember now. But when I tried now, it gave the following output:

```
Changed current directory to /Users/johnB/.composer
Using version ^0.3.2 for daux/daux.io
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

So I guess it is updated now. Is the command still `./daux.phar -f html-file` ?

**Comment by onigoetz** [comment]
I repaired single-file output in the current master, I don't plan to add PDF export for the moment though
