### ISSUE TITLE
Difficulty Setting Custom Favicon

### ISSUE THREAD

**Issue by ThePoetics** [dauxio/daux.io#409]
I'm trying to use a simple `style.css` to overwrite the default favicon in the daux-navy theme (per [Creating a Theme](https://daux.io/For_Developers/Creating_a_Theme.html)), but I can't find the right syntax to make it load.

I have the following in my style.css (located in the root of my documents folder), and have confirmed the file's location on both the filesystem and via the browser:
```
{
    "favicon": "<base_url>images/favicon-32x32.png"
}
```

If I create a custom theme I can set the favicon just fine, but I wanted to avoid maintaining my own theme for just this one change.

*Side Request:* Do you have your documentation's dark mode css available anywhere? I really like how clean it looks

**Comment by onigoetz** [comment]
Hi @ThePoetics, sorry for the long delay in answering.

## Favicon

The configuration needs to be in a `config.json` there is no option around that.

Here is the shortest way to achieve this, create a `themes/not_daux` theme with the following

* `img/favicon-red.png`: copied from the daux theme
* `config.json`:
  ```json
  {
      "favicon": "<theme_url>img/favicon-red.png"
  }
  ```

Then you need to change your `docs/config.json` to `"theme": "not_daux"` to use that newly created theme.

Which generates the following markup:
```html
<link rel="icon" href="/themes/not_daux/img/favicon-red.png" type="image/x-icon">
```

You can then copy the daux theme for the rest of the styles and change whatever you like to fit your design.

## Dark mode
For the dark theme; I used the ideas from [Joshua W. Comeau's article](https://www.joshwcomeau.com/react/dark-mode/) on how to switch from light to dark. For the colors themselves I went with trial and error, and some tricks I learned from [Adam Wathan's book; Refactoring UI](https://www.refactoringui.com/).

I tried as much as possible to put everything in CSS variables, this makes the switch much easier and keeps the amount of CSS needed low.

This is where all Dark mode variables are : https://github.com/dauxio/daux.io/blob/master/src/css/theme_daux/_variables.scss#L147 and the Js for the toggle: https://github.com/dauxio/daux.io/blob/master/src/js/theme_daux/dark_mode.js.

**Comment by ThePoetics** [comment]
Thank you!

**Comment by onigoetz** [comment]
you're welcome :)
