### ISSUE TITLE
Docker: Fatal error: Uncaught Error: Call to undefined method [...] getTerminalDimensions

### ISSUE THREAD

**Issue by tomgidden** [dauxio/daux.io#49]
Running
```
$ docker pull daux/daux.io
latest: Pulling from daux/daux.io
Digest: sha256:f2fb6ad79d09aa3556895304071714ebb0403531c94e9286f7ccb828a173ce1c
Status: Image is up to date for daux/daux.io:latest

$ docker run --rm -it -w /build -v src:/build/docs -v build:/build/static daux/daux.io daux
```

gives: 
```
Fatal error: Uncaught Error: Call to undefined method Todaymade\Daux\Console\Application::getTerminalDimensions() in /daux/libs/Console/Generate.php:46
Stack trace:
#0 /daux/vendor/symfony/console/Command/Command.php(252): Todaymade\Daux\Console\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /daux/vendor/symfony/console/Application.php(865): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /daux/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Todaymade\Daux\Console\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /daux/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput) in /daux/libs/Console/Generate.php on line 46
```

Running the earlier 0.7.2 image works:
```
docker run --rm -it -w /build -v src:/build/docs -v build:/build/static daux/daux.io:0.7.2 daux 
```
so my guess is a change in Symfony in the meantime.

**Comment by woei66** [comment]
I have the same issue and I didn't use docker, I used php cli to execute "daux generate" under the docs/ folder.

**Comment by brettswift** [comment]
+1.  

I might want to use this on a non-nodejs application.   Docker is a great option to generate daux. 

After visiting this project,  grabbing the example out of the examples folder, and not being able to get something up with the docker image..    I'm a bit deterred from using it.  I'll give it another shot when this bug is fixed. 

I can reproduce this error with something like: 

1. `git clone this.repo`
2. `cp -r examples/multilanguage ../testproject/docs`
3. `docker run --rm -it -w /build -v "$PWD":/build daux/daux.io daux`
4. same error as in this thread.

**Comment by tomgidden** [comment]
@brettswift If you use `daux/daux.io:0.7.2` rather than `daux/daux.io` (ie. `:latest`) it seems to work. Not ideal, but there aren't that many differences between the latest and `0.7.2`.

In fact, I wonder if the most recent commit (merging #43) caused this fault: it includes a change from Symfony `3.3.x` to `4.0`.

**Comment by brettswift** [comment]
Thanks @tomgidden .   

I see there's a travis.yml.     Might be good to get this scenario tested.  I'd contribute but can't get to it for a bit.

**Comment by onigoetz** [comment]
Fixed. Sorry for the delay
