### ISSUE TITLE
Use Alpine php Docker image instead

### ISSUE THREAD

**Issue by mfilotto** [dauxio/daux.io#5]
It would be great to reduce image size and get rid of so many vulnerabilities contained in php:7 by using an alpine base image

**Comment by mfilotto** [comment]
```
FROM php:7

RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*
```
would become

```
FROM php:7-alpine

RUN apk add --no-cache unzip
```

**Comment by onigoetz** [comment]
Hello,

yes sure I could have a look at that.

Just out of curiosity, do you have a link on the vulnerabilities you mention on the main docker image ?

**Comment by mfilotto** [comment]
Hello,
Oh thanks.
It can been seen directly on Docker Hub or Docker store.
Go on tags page of the official php image.
You could have to try more than once as the scan results do not show up all the time.
You can also scan with clair on your laptop

**Comment by mfilotto** [comment]
Here are the links
- [Tags list from Docker Hub](https://hub.docker.com/r/library/php/tags/)
- [Tags list from Docker Store](https://store.docker.com/images/php/plans/f78bd971-b049-4362-804a-51c18502ac29?tab=tags)

Vulnerabilities detailed:
- [Detail for php:7](https://store.docker.com/images/php/plans/f78bd971-b049-4362-804a-51c18502ac29/scans/library/php/7)
- [Detail for php:7-alpine](https://store.docker.com/images/php/plans/f78bd971-b049-4362-804a-51c18502ac29/scans/library/php/7-alpine)

**Comment by onigoetz** [comment]
Hi, I made the change and pushed to master, the image should build soon
