### ISSUE TITLE
verbose doesnt work

### ISSUE THREAD

**Issue by laapsaap** [dauxio/daux.io#52]
Hi,

Daux is giving me some headache so I decide to do triple -vvv and --verbose 2 and --verbose 3. But it never really show me any verbose messages that I am expecting. 

Like generating the static html. I removed the complete templates directory and it somehow still generate the static pages. So where does HTML come from?  On my laptop if I change templates directory it will affect the static html. But doing exactly the same on the server doesnt. I would expect if I remove the complete templates directory, that it wouldnt work.   

Verbose mode would help a lot...

**Comment by onigoetz** [comment]
Hello,

sure, I can add information of what template is used to generate files in verbose mode.

For your specific case, how did you install daux ? (looking at your report in #53 I suppose it's a .phar) The .phar archive has the templates embedded inside, but you can override them with a theme. 

You can check the documentation here to see how themes and templates interact : https://dauxio.github.io/For_Developers/Creating_a_Theme.html#page_Overriding-templates

**Comment by laapsaap** [comment]
Yes thanks it took me some time to figure out I got a wrong version, due to an older php version. Thats why simple things like -v and --verbose should have given me instant clues about it. But I figured it out eventually. So now using the latest version, expected behavior is back again 👍
