### ISSUE TITLE
breadcrumb drops a directory when its has a same name.

### ISSUE THREAD

**Issue by laapsaap** [dauxio/daux.io#54]
Hi there again :)

I noticed some unexpected behavior, not sure if its intended or not.
So the breadcrumb feature works fine in general, but in one case its a bit odd.

So lets say this is my directory hierachy for docs

for ./docs/office/webserver/dc1/bla.md
the breadcrumb trail wil be:  office > webserver > dc1 > bla

for. /docs/office/webserver/office/bla.md
the breadcrumb trail wil be:  office > webserver > bla

So in the second case, when the directory has the same name further down the hierachy, it drops it in the breadcrumb. Is this a bug? In the MENU its listed correctly.

ps: I am using latest version.

**Comment by laapsaap** [comment]
ahh it must be a bug, because $page['breadcrumb_trail'] is an array and uses the DIRECTORY NAME as the key. So in the second example its only an array  with two keys. Oops.

**Comment by onigoetz** [comment]
Oh, good catch :) I'll have a look

**Comment by onigoetz** [comment]
That was an easy fix, it's released in 0.7.4
