### ISSUE TITLE
getFrontMatter() invoked multiple times

### ISSUE THREAD

**Issue by aedart** [dauxio/daux.io#55]
In an attempt to design a possible cache solution (#51), I found that `\Todaymade\Daux\Tree\Content::getFrontMatter()` might be invoked multiple times:

* From `\Todaymade\Daux\Tree\Content::getContent()`
* And from `\Todaymade\Daux\Tree\Content::parseAttributes()`

I'm not too sure about this being a defect - But if I read the code correctly, then markdown content is parsed twice, which does have some negative effect on performance. Should `getFrontMatter()` not return evt. previously rendered content, if any is available?

**Comment by onigoetz** [comment]
Hello,

I made the change to call it only once.

The change doesn't give a big performance boost : https://blackfire.io/profiles/f105b698-8393-4058-8707-ea2f2b1ee69e/graph

2% is not a lot, but it's still something :)
