### ISSUE TITLE
0.7.3-4 Notices

### ISSUE THREAD

**Issue by seigieu** [dauxio/daux.io#57]
I have alot of notices after upgrading to newest DAUX

	PHP Notice:  Undefined property: Todaymade\Daux\Config::$docs_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$docs_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$valid_content_extensions in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$valid_content_extensions in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$mode in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$mode in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$local_base in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$local_base in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$templates in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$templates in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$themes_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$themes_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$title in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$title in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$tagline in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$tagline in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$author in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$author in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$image in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$image in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$languages in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$languages in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$format in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$format in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$processor in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$processor in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$ignore in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$ignore in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$language in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$language in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$strings in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$strings in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$timezone in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$timezone in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$live in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$live in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$html in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$html in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$confluence in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$confluence in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$themes_path in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$themes_path in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$tree in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$tree in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$index in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$index in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$entry_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$entry_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$theme in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$theme in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$request in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$request in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$current_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$current_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$docs_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$docs_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$valid_content_extensions in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$valid_content_extensions in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$mode in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$mode in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$local_base in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$local_base in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$templates in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$templates in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$themes_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$themes_directory in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$title in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$title in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$tagline in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$tagline in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$author in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$author in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$image in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$image in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$languages in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$languages in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$format in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$format in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$processor in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$processor in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$ignore in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$ignore in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$language in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$language in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$strings in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$strings in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$timezone in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$timezone in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$live in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$live in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$html in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$html in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$confluence in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$confluence in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$themes_path in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$themes_path in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$tree in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$tree in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$index in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$index in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$entry_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$entry_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$theme in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$theme in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$request in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$request in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
	PHP Notice:  Undefined property: Todaymade\Daux\Config::$current_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

	Notice: Undefined property: Todaymade\Daux\Config::$current_page in C:\Users\user\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

**Comment by seigieu** [comment]
I'm sorry but I don't upgrade anymore. I stay with 0.6.x as it's most stable and tbh don't have time atm to play with it. Need it stable. Will try to test newer versions when I have more time available.

**Comment by seigieu** [comment]
PS: You can close it for time being if you want.

**Comment by onigoetz** [comment]
Thanks for the feedback, I'll keep an eye out for these errors

**Comment by seigieu** [comment]
Hello @onigoetz , sorry for not writing so long, alot of work, couldn't find time to play with daux... but now I did.
About jQuery not defined error (other ticket): Basically I think my problem was incompatible template, I was using 6.0 daux theme css overwrite, and didn't repalce it with new one. After updating new CSS and assigning new colors it works fine.

And this happens sometimes... but 2nd run of `daux generate` command passes without flaws. Additionally, those errors do not pervent docs from generating.

```Notice: Undefined property: Todaymade\Daux\Config::$templates in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
PHP Notice:  Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

Notice: Undefined property: Todaymade\Daux\Config::$index_key in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

Notice: Undefined property: Todaymade\Daux\Config::$base_page in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
PHP Notice:  Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232

Notice: Undefined property: Todaymade\Daux\Config::$base_url in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232
PHP Notice:  Undefined property: Todaymade\Daux\Config::$themes_directory in C:\Users\Grzegorz\AppData\Roaming\Composer\vendor\myclabs\deep-copy\src\DeepCopy\DeepCopy.php on line 232```

**Comment by onigoetz** [comment]
Hi @seigieu, no worries, I know what it is :)

Is your documentation public somewhere so that I can do some tests ?
