### ISSUE TITLE
[InvalidArgumentException] Could not find package daux io/daux.io

### ISSUE THREAD

**Issue by Maxcorp** [dauxio/daux.io#6]
Hello!

I've got an error, when i try to install daux by composer:

[InvalidArgumentException]                                                                           
  Could not find package dauxio/daux.io at any version for your minimum-stability (stable). Check the  
   package spelling or your minimum-stability                       

For install i use: composer global require dauxio/daux.io

**Comment by mattie47** [comment]
Also having this issue.

**Comment by philicevic** [comment]
Same problem here..

**Comment by onigoetz** [comment]
Hello, I'm sorry, the packagist package is `daux/daux.io`.
The documentation has been updated accordingly
