### ISSUE TITLE
Uncaught Error: Call to undefined method Symfony\Component\Process\ ProcessUtils::escapeArgument()

### ISSUE THREAD

**Issue by chw502** [dauxio/daux.io#61]
I am trying to upgrade my daux to 0.7.4. When I run `daux serve`, I got this error: `Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument() in xxxxx\Composer\vendor\daux\daux.io\libs\Console\Serve.php:45`. 

I tried to dig into the code and find that  `ProcessUtils::escapeArgument(__DIR__ . '/../../')` is using in `Serve.php`. Perphas this function is [removed](https://github.com/symfony/process/commit/8bdb5476df7d0f1f5243ff1a773173d81c23f23c#diff-a2f61bc22edcb07f620201b55413f352) in `Symfony\ProcessUtils`?

**Comment by rslhdyt** [comment]
same here

**Comment by cambierr** [comment]
https://github.com/dauxio/daux.io/pull/64 fix it. I hope it will be merged and a release will be made

**Comment by onigoetz** [comment]
Hello, thanks for the report and pull request, I'll have a look this week

**Comment by onigoetz** [comment]
It's fixed in 0.7.5, sorry for the delay
