### ISSUE TITLE
hhvm compatibility

### ISSUE THREAD

**Issue by 3qdev** [dauxio/daux.io#66]
Since Version 0.7.3 daux.io Package on packagist.org require php >= 7.1.3
Is that really necessary? 
With the latest hhvm 3.24-lts (3.24.8) I can install only version 0.7.2 of daux via composer.

**Comment by onigoetz** [comment]
Hello, yes I dropped the support for HHVM, as we now use Symfony 4 components, and Symfony themselves have stopped supporting HHVM : https://symfony.com/blog/symfony-4-end-of-hhvm-support

Sorry if that impacts you negatively
