### ISSUE TITLE
Missing rules in CSS

### ISSUE THREAD

**Issue by aabiabdallah** [dauxio/daux.io#7]
I just downloaded the master branch files and the CSS files do not contain rules for .Navbar__brand which is assigned as a class in generated doc files. There is a new rule for .Navbar .Brand which doesn't seem to be used.

**Comment by onigoetz** [comment]
Hi,

You are probably using the .phar version of the library. It is not supported anymore and outdated.

You should install the project with `composer global require daux/daux.io`
