### ISSUE TITLE
We're using Daux!

### ISSUE THREAD

**Issue by enricobono** [dauxio/daux.io#70]
Hi gals and guys.
We're using Daux (if you were wondering 😂).

I'd like to add our documentation: https:doc.soisy.it to your readme. Is it feasible?
We are using a custom theme.

Thanks anyway,
Enrico

**Comment by onigoetz** [comment]
Hello,

I added you to the list: https://dauxio.github.io/daux.io/Getting_Started.html#page_Demos

and thanks again for your contributions :)

**Comment by enricobono** [comment]
You are most welcome :)
Thank you guys
