### ISSUE TITLE
useful improvements for the search function

### ISSUE THREAD

**Issue by celbasi** [dauxio/daux.io#71]
hello
I think it would also be useful to show and highlight the searched words in the search results. 
You should also get directly to the searched word and not to the beginning of the page. With longer entries one does not find the term on the side. 
The search could be also less knitted so that word parts or combinations are found more simply or if several words are entered which do not agree hundred percent with the text.
The results should be sorted by relevance and not chronically.
Thank you

**Comment by onigoetz** [comment]
Currently, the search uses a very dumb algorithm, I plan to improve it in the future, but not right now.

**Comment by onigoetz** [comment]
Consider using https://github.com/nextapps-de/flexsearch to improve search results

**Comment by onigoetz** [comment]
The next release will contain flexsearch, I still need to highlight words
