### ISSUE TITLE
Daux.io deployment and configuration

### ISSUE THREAD

**Issue by axe1man** [dauxio/daux.io#73]
Hello, 
First of all, thanks a lot for a great framework for online help. 
Now I'm trying to switch to new version of daux.io and encountered some issues, that I already resolved manually. But I think I should let you know, so that users do not waste time on that stuff. Everything should work out of the box.

Please find below instructions and recommendations on how to fix  those issues:
- you might need to update package content for Composer
- you might need to update Installation instructions for daux.io.
--------------------------
- **{DAUX}** - Daux.io folder with help: C:/Workspace/daux.io/
- **{COMPOSER}** - Daux.io folder in Composer folder: C:/User/Oleksandr/AppData/Roaming/Composer/vendor/daux/daux.io/
- Command: daux generate
--------------------------
**Issue 1:**
- Getting_Started.htmlPHP Fatal error:  Class 'Todaymade\Daux\FormatDate' not found in C:\Workspace\daux.io\templates\content.php on line 8
**Solution:**
Copy {DAUX}/libs/FormatDate.php into {COMPOSER}/libs
--------------------------
**Issue 2:**
- Getting_Started.htmlPHP Fatal error:  Class 'IntlDateFormatter' not found in C:\Users\Oleksandr\AppData\Roaming\Composer\vendor\daux\daux.io\libs\FormatDate.php on line 9
**Solution:**
Uncomment following line in your php.ini in the PHP installation folder:
extension=php_intl.dll
--------------------------------
**Issue 3:**
- Apart from that, libs folder content in {COMPOSER} missing some other files, that exist in {DAUX} folder.
--------------------------------

**Comment by onigoetz** [comment]
Thanks for the report, sorry for not answering sooner, I've since made the changes in the documentation to address this or to make sure it doesn't break.

Apart from that it seems from your report that you have a local version of daux and a global version which get mixed up.

Try updating your global installation as well as your local one.
