### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by wyred** [dauxio/daux.io#76]
Would it be possible for to update the dependency for league/commonmark?

I'm installing this per project instead of global so that I can minimize server configuration, and get it to auto generate documentation each time my web app is deployed. (I've tested this on another project and it works fine.)

It currently clashes with another package I have installed which is `graham-campbell/markdown`

    Problem 1
      - Installation request for daux/daux.io ^0.8.1 -> satisfiable by daux/daux.io[0.8.1].
      - Conclusion: remove league/commonmark 0.18.0
      - Conclusion: don't install league/commonmark 0.18.0
      - daux/daux.io 0.8.1 requires league/commonmark ^0.17 -> satisfiable by league/commonmark[0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5].
      - don't install league/commonmark 0.17.0|don't install league/commonmark 0.18.0
      - don't install league/commonmark 0.17.1|don't install league/commonmark 0.18.0
      - don't install league/commonmark 0.17.2|don't install league/commonmark 0.18.0
      - don't install league/commonmark 0.17.3|don't install league/commonmark 0.18.0
      - don't install league/commonmark 0.17.4|don't install league/commonmark 0.18.0
      - don't install league/commonmark 0.17.5|don't install league/commonmark 0.18.0
      - Installation request for league/commonmark (locked at 0.18.0) -> satisfiable by league/commonmark[0.18.0].

**Comment by onigoetz** [comment]
Hi @wyred 
I tried to update a week ago, but a package we depend on (https://packagist.org/packages/webuni/commonmark-table-extension) requires commonmark 0.16/0.17

There is a pull-request open on their side to fix this : https://github.com/webuni/commonmark-table-extension/pull/17

I subscribed to it and as soon as it is resolved and released, I'll update Daux

**Comment by bbashy** [comment]
This has been merged.

**Comment by onigoetz** [comment]
Cool, I'll update in the next few days

**Comment by onigoetz** [comment]
released in 0.9.0
