### ISSUE TITLE
Adding a login system

### ISSUE THREAD

**Issue by luigeek** [dauxio/daux.io#77]
As mentioned some time ago in the original project (initially requested in: https://github.com/justinwalsh/daux.io/issues/37) , It would be great if you can add a simple login system to this documentation app. Wee have sensitive information that can't be opened to the world.

Using .htaccess / .htpasswd files could be an alternative, but that limits what kind of web server software can used.

We thought another possibility is to generate the output files with a .php extension insted of HTML, then we can require a file at the beggining that handles user validation.

Any feedback on this is highly appeciated.

**Comment by onigoetz** [comment]
Hi,

thanks for the interest in Daux.io, I don't plan to add login.

Many webservers offer a password access feature, it's not mandatory to use Apache for this.
