### ISSUE TITLE
Search does not work anymore

### ISSUE THREAD

**Issue by 3qdev** [dauxio/daux.io#85]
can you see why the search does not work anymore on

https://docs.3q.video/

there is a error in Console output: window.searchTranslation is undefined

we are on version 0.8.1

**Comment by MasterOdin** [comment]
You probably need to add:
https://github.com/dauxio/daux.io/blob/7d8d5c86cfce682166bb55bc2298f2658c75cdc3/templates/layout/00_layout.php#L66-L87
to the bottom of your layout before you load:
```
<script type="text/javascript" src="tipuesearch/tipuesearch.js"></script>
```

**Comment by 3qdev** [comment]
Thanks a lot, it works

**Comment by onigoetz** [comment]
Nice theme, can I feature your documentation in our documentation ?

**Comment by 3qdev** [comment]
Yes please!
