### ISSUE TITLE
Warn invalid filenames

### ISSUE THREAD

**Issue by willysunny** [dauxio/daux.io#86]
Just a small bug that was overlooked.

In the event if there's a # in the filename, it'll get parsed and generated normally. 

EG: Page#134.md -> Page#134.html

However, when it's on http, that's another story.

http://example.com/daux/Page#134.html <-- this is actually reading http://example.com/daux/Page, and then look for &lt;a name="134.html"&gt;

**Comment by onigoetz** [comment]
Wow, okay, I didn't even know you could name files with a # :o 

I'll make sure to add a warning for this filename and other non-url friendly characters.

**Comment by willysunny** [comment]
You can name files with # on both unix and windows file system, just fyi

**Comment by onigoetz** [comment]
I released version [0.9.2](https://github.com/dauxio/daux.io/releases/tag/0.9.2) With a fix to the # in filename issue.
